<section id="jadwal">
	<h1 class="fs-5 text-center">Jadwal Piket</h1>
	<div class="container table-responsive">
		<table class="table table-striped mt-2">
			<thead>
				<tr>
					<th>Senin</th>
					<th>Selasa</th>
					<th>Rabu</th>
					<th>Kamis</th>
					<th>Jumat</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
						<ol class="ps-3">
							<li>Alfu</li>
							<li>Anggi</li>
							<li>Amel</li>
							<li>Asinta</li>
							<li>Bunga</li>
							<li>Bylla</li>
							<li>Bayu</li>
							<li>Dimas</li>
						</ol>
					</td>
				    <td>
				        <ol>
				            <li>Desla</li>
				            <li>Eky</li>
				            <li>Enggal</li>
				            <li>Intan</li>
				            <li>Afi</li>
				            <li>Fifah</li>
				            <li>Ilham</li>
				        </ol>
				    </td>
				    <td>
				        <ol>
				            <li>Puji</li>
				            <li>Luthfi</li>
				            <li>Lulu</li>
				            <li>Mei</li>
				            <li>Nandya</li>
				            <li>Natasyah</li>
				            <li>Rava</li>
				        </ol>
				    </td>
				    <td>
				        <ol>
				            <li>Putri</li>
				            <li>Reva</li>
				            <li>Salsa</li>
				            <li>Salwa</li>
				            <li>Caca</li>
				            <li>Sarah</li>
				            <li>Rifki</li>
				        </ol>
				    </td>
				    <td>
				        <ol>
				            <li>Sekar</li>
				            <li>Syafira</li>
				            <li>Umi</li>
				            <li>Veli</li>
				            <li>Yumna</li>
				            <li>Zahra</li>
				            <li>Aminnn</li>
				        </ol>
				    </td>
				</tr>
			</tbody>
		</table>
	</div>
</section>